version: '3'
services:

    beater:
        build: .
        environment:
            - TYPE=beat
        volumes:
            - ./celery_app/:/app/celery_app/ 
        depends_on:
            - rabbit
            - worker

    worker:
        build: .
        environment:
            - TYPE=worker
        volumes:
            - ./celery_app/:/app/celery_app/ 
        depends_on:
            - rabbit
            - graphite
            - mongo
    
    rabbit:
        image: rabbitmq:latest
        ports:
            - "5672:5672"
        environment:
          - TZ=Europe/Warsaw

    graphite:
        image: graphiteapp/graphite-statsd
        environment:
            - discovery.type=single-node
            - TZ=Europe/Warsaw
        volumes:
            - ./graphite/whisper:/opt/graphite/storage/whisper
        ports:
            - 80:80
            - 2003-2004:2003-2004 
            - 2023-2024:2023-2024 
            - 8125:8125/udp 
            - 8126:8126 
        restart: always

    grafana:
        image: grafana/grafana
        volumes:
            - ./grafana-storage:/var/lib/grafana
            - ./grafana-storage/config/dashboards:/var/lib/grafana/dashboards
        ports:
        - 3000:3000
        depends_on:
        - graphite

    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=example
        volumes:
          - mongodata:/data/db

        ports:
          - 27017:27017
        restart: unless-stopped

    mongoex:
        image: mongo-express
        environment:
        - ME_CONFIG_MONGODB_SERVER=mongo
        - ME_CONFIG_MONGODB_PORT=27017
        - ME_CONFIG_MONGODB_ADMINUSERNAME=root
        - ME_CONFIG_MONGODB_ADMINPASSWORD=example
        ports:
        - 8081:8081
        depends_on:
        - mongo
        restart: unless-stopped

    pyspark:
        image: jupyter/pyspark-notebook
        volumes:
            - ../lab10-kr-pt7-JanKulbinski/notebooks:/home/jovyan/work
        ports:
            - 8888:8888
        entrypoint: start.sh jupyter notebook --NotebookApp.token=''
        depends_on:
        - mongo

volumes:
  mongodata: